export { default as Home } from './Home'
export { default as Lounge } from './Lounge'
export { default as Team } from './Team'
export { default as Room } from './Room'
export { default as Result } from './Result'
